-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Dec 20, 2015 at 05:50 PM
-- Server version: 10.1.8-MariaDB
-- PHP Version: 5.6.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mrcatfish`
--

-- --------------------------------------------------------

--
-- Table structure for table `kiatbisnis`
--

CREATE TABLE `kiatbisnis` (
  `node` varchar(11) NOT NULL,
  `trik` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `kiatbisnis`
--

INSERT INTO `kiatbisnis` (`node`, `trik`) VALUES
(' p3m1s2f1f3', 'Marterial kolam hanya mampu bertahan maks. 4 bulan\r\nBambu lebih mudah lapuk di musim hujan, penggantian bambu yang lapuk sangat perlu diperhatikan\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n\r\nKonsentrasi pakan daging tidak terlalu berdampak pada kolam, namun akan membuat perkembangan ikan lele akan semakin cepat'),
('p0', '----------------------------------'),
('p1m1s1f1', 'Marterial kolam hanya mampu bertahan maks. 6 bulan\r\nKerusakan kolam dapat ditangani dengan penggantian bambu\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n'),
('p1m1s2f1', 'Marterial kolam hanya mampu bertahan maks. 4 bulan\r\nBambu lebih mudah lapuk di musim hujan, penggantian bambu yang lapuk sangat perlu diperhatikan\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70\r\n'),
('p1m2s1f1', 'Material kolam mampu bertahan selama 2 tahun\r\nBatu bata akan lebih cepat retak dan menyebabkan kebocoran di musim kemarau, penambalan kolam dengan semen perlu dilakukan untuk mengatasi masalh ini.\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam sedalam 25 cm untuk mencegah amblesnya tanah\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n'),
('p1m2s2f1', 'Material kolam mampu bertahan selama 2 tahun\r\nKerusakan kolam dapat ditangani dengan penambalan kolam dengan semen\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam \r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)'),
('p2m1s1f2', 'Marterial kolam hanya mampu bertahan maks. 6 bulan\r\nKerusakan kolam dapat ditangani dengan penggantian bambu\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nDengan konsentrasi pakan konsentrat, maka ada beberapa hal yang perlu diperhatikan:\r\nair kolam akan cepat keruh, sehingga Anda perlu mengganti air kolam perminggu\r\nperkembangan ikan biasa saja, tidak ada pemacu perkembangan.\r\n'),
('p2m1s1f3', 'Marterial kolam hanya mampu bertahan maks. 6 bulan\r\nKerusakan kolam dapat ditangani dengan penggantian bambu\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nKonsentrasi pakan daging tidak terlalu berdampak pada kolam, namun akan membuat perkembangan ikan lele akan semakin cepat\r\n'),
('p2m1s2f2', 'Marterial kolam hanya mampu bertahan maks. 4 bulan\r\nBambu lebih mudah lapuk di musim hujan, penggantian bambu yang lapuk sangat perlu diperhatikan\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nDengan konsentrasi pakan konsentrat, maka ada beberapa hal yang perlu diperhatikan:\r\nair kolam akan cepat keruh, sehingga Anda perlu mengganti air kolam perminggu\r\nperkembangan ikan biasa saja, tidak ada pemacu perkembangan.'),
('p2m1s2f3', 'Marterial kolam hanya mampu bertahan maks. 4 bulan\r\nBambu lebih mudah lapuk di musim hujan, penggantian bambu yang lapuk sangat perlu diperhatikan\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nKonsentrasi pakan daging tidak terlalu berdampak pada kolam, namun akan membuat perkembangan ikan lele akan semakin cepat'),
('p2m2s1f2', 'Material kolam mampu bertahan selama 2 tahun\r\nBatu bata akan lebih cepat retak dan menyebabkan kebocoran di musim kemarau, penambalan kolam dengan semen perlu dilakukan untuk mengatasi masalh ini.\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam sedalam 25 cm untuk mencegah amblesnya tanah\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nDengan konsentrasi pakan konsentrat, maka ada beberapa hal yang perlu diperhatikan:\r\nair kolam akan cepat keruh, sehingga Anda perlu mengganti air kolam perminggu\r\nperkembangan ikan biasa saja, tidak ada pemacu perkembangan.'),
('p2m2s1f3', 'Material kolam mampu bertahan selama 2 tahun\r\nBatu bata akan lebih cepat retak dan menyebabkan kebocoran di musim kemarau, penambalan kolam dengan semen perlu dilakukan untuk mengatasi masalh ini.\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam sedalam 25 cm untuk mencegah amblesnya tanah\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nKonsentrasi pakan daging tidak terlalu berdampak pada kolam, namun akan membuat perkembangan ikan lele akan semakin cepat.'),
('p2m2s2f2', 'Material kolam mampu bertahan selama 2 tahun\r\nKerusakan kolam dapat ditangani dengan penambalan kolam dengan semen\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam \r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nDengan konsentrasi pakan konsentrat, maka ada beberapa hal yang perlu diperhatikan:\r\nair kolam akan cepat keruh, sehingga Anda perlu mengganti air kolam perminggu\r\nperkembangan ikan biasa saja, tidak ada pemacu perkembangan'),
('p2m2s2f3', 'Material kolam mampu bertahan selama 2 tahun\r\nKerusakan kolam dapat ditangani dengan penambalan kolam dengan semen\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam \r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nKonsentrasi pakan daging tidak terlalu berdampak pada kolam, namun akan membuat perkembangan ikan lele akan semakin cepat'),
('p3m1s1f1f2', 'Marterial kolam hanya mampu bertahan maks. 6 bulan\r\nKerusakan kolam dapat ditangani dengan penggantian bambu\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n\r\nDengan konsentrasi pakan konsentrat, maka ada beberapa hal yang perlu diperhatikan:\r\nair kolam akan cepat keruh, sehingga Anda perlu mengganti air kolam perminggu\r\nperkembangan ikan biasa saja, tidak ada pemacu perkembangan.'),
('p3m1s1f1f3', 'Marterial kolam hanya mampu bertahan maks. 6 bulan\r\nKerusakan kolam dapat ditangani dengan penggantian bambu\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n\r\nKonsentrasi pakan daging tidak terlalu berdampak pada kolam, namun akan membuat perkembangan ikan lele akan semakin cepat'),
('p3m1s2f1f2', 'Marterial kolam hanya mampu bertahan maks. 4 bulan\r\nBambu lebih mudah lapuk di musim hujan, penggantian bambu yang lapuk sangat perlu diperhatikan\r\nAgar kolam mampu menahan beban (air & ikan) maka pinggiran kolam harus diberi pasak\r\nPasak utama terdapat di sudut kolam\r\nPasak penunjang berjumlah 14 pasak (3 pasak penunjang untuk masing-masing sisi terpendek kolam dan 4 pasak penunjang untuk masing masing sisi terpanjang kolam)\r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n\r\nDengan konsentrasi pakan konsentrat, maka ada beberapa hal yang perlu diperhatikan:\r\nair kolam akan cepat keruh, sehingga Anda perlu mengganti air kolam perminggu\r\nperkembangan ikan biasa saja, tidak ada pemacu perkembangan.'),
('p3m2s1f1f2', 'Material kolam mampu bertahan selama 2 tahun\r\nBatu bata akan lebih cepat retak dan menyebabkan kebocoran di musim kemarau, penambalan kolam dengan semen perlu dilakukan untuk mengatasi masalh ini.\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam sedalam 25 cm untuk mencegah amblesnya tanah\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n\r\nDengan konsentrasi pakan konsentrat, maka ada beberapa hal yang perlu diperhatikan:\r\nair kolam akan cepat keruh, sehingga Anda perlu mengganti air kolam perminggu\r\nperkembangan ikan biasa saja, tidak ada pemacu perkembangan.'),
('p3m2s1f1f3', 'Material kolam mampu bertahan selama 2 tahun\r\nBatu bata akan lebih cepat retak dan menyebabkan kebocoran di musim kemarau, penambalan kolam dengan semen perlu dilakukan untuk mengatasi masalh ini.\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam sedalam 25 cm untuk mencegah amblesnya tanah\r\n\r\nAgar suhu air kolam tetap stabil di musim panas, maka :\r\nKolam perlu dibuatkan kanopi (yang terbuat dari jaring-jaring) untuk menghindari sinar matahari langsung pada siang hari\r\nKanopi kolam (jaring-jaring) berjarak 180 cm diatas kolam\r\nPenjadwalan buka tutup kolam degnan menggunakan terpal. Buka tutup kolam pagi (buka 7-10, tutup 10-16) sore (buka 16-19 tutup 19-7)\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n\r\nKonsentrasi pakan daging tidak terlalu berdampak pada kolam, namun akan membuat perkembangan ikan lele akan semakin cepat'),
('p3m2s2f1f2', 'Material kolam mampu bertahan selama 2 tahun\r\nKerusakan kolam dapat ditangani dengan penambalan kolam dengan semen\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam \r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n\r\nDengan konsentrasi pakan konsentrat, maka ada beberapa hal yang perlu diperhatikan:\r\nair kolam akan cepat keruh, sehingga Anda perlu mengganti air kolam perminggu\r\nperkembangan ikan biasa saja, tidak ada pemacu perkembangan.'),
('p3m2s2f1f3', 'Material kolam mampu bertahan selama 2 tahun\r\nKerusakan kolam dapat ditangani dengan penambalan kolam dengan semen\r\nAgar kolam mampu menahan beban (air & ikan) maka perlu dibuat pondasi kolam \r\n\r\nVolume air kolam akan bertambah seiring datangnya hujan pengecekan terhadap pipa pembuangan air otomatis perlu dilakukan agar kelebihan volume air dapat terkendali\r\n\r\nIkan akan mudah terserang cacar, sehingga penggantian air kolam secara menyeluruh perlu dilakukan segera setelah hujan\r\n\r\nPakan cacing sutra murni hingga umur 15 hari, setelah 15 hari pakan diganti dengan konsentrat udang hingga hari ke 20, setelah hari ke 20 diganti ke pf 500 (10 hari), pf 800 (10 hari), pf 1000 (10 hari), strip 2 (hingga panen / hari ke 70)\r\n\r\nKonsentrasi pakan daging tidak terlalu berdampak pada kolam, namun akan membuat perkembangan ikan lele akan semakin cepat');

-- --------------------------------------------------------

--
-- Table structure for table `recentresult`
--

CREATE TABLE `recentresult` (
  `id_hasil_analisa` int(7) NOT NULL,
  `ukuran_kolam` varchar(75) NOT NULL,
  `material_kolam` varchar(10) NOT NULL,
  `musim` varchar(10) NOT NULL,
  `pilihan_pakan` varchar(10) NOT NULL,
  `rincian_analisa` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `kiatbisnis`
--
ALTER TABLE `kiatbisnis`
  ADD PRIMARY KEY (`node`);

--
-- Indexes for table `recentresult`
--
ALTER TABLE `recentresult`
  ADD PRIMARY KEY (`id_hasil_analisa`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recentresult`
--
ALTER TABLE `recentresult`
  MODIFY `id_hasil_analisa` int(7) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
